parameters:
#    parameter_name: value

services:
    app.mailer:
        class:          AppBundle\Service\Mailer
        arguments:
          - "@mailer"
          - "@templating"
    
    app.registration_manager:
        class:          AppBundle\Service\RegistrationManager
        arguments:
          - "@security.password_encoder"
          - "@doctrine.orm.entity_manager"
          - "@app.mailer"
          - "@app.role_manager"
    
    app.attendance_updater:
        class:          AppBundle\Service\AttendanceUpdater
        arguments:
          - "@doctrine.orm.entity_manager"

    # datatransformer before saving to image
    app.form.type.picture:
        class:          AppBundle\Form\UploadPictureType
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - 
                name: form.type

    app.twig_extension:
        class:          AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    app.role_manager:
        class:          AppBundle\Service\RoleManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%sadmin_mails%"

    app.statistics_manager:
        class:          AppBundle\Service\StatisticsManager
        arguments:
            - "@doctrine.orm.entity_manager"

    app.factorytour_manager:
        class:          AppBundle\Service\FactoryTourManager
        arguments:
          - "@doctrine.orm.entity_manager"