<?php

namespace AppBundle\Entity;

use AppBundle\Utils\ChoiceList\CategoryChoiceLoader;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSortedCategory()
    {
        $categories = (new CategoryChoiceLoader())->getChoices();
        $em = $this->getEntityManager();
        
        foreach($categories as $key => $value) {
            $projects[$value] = $em->createQuery(
            'SELECT p
             FROM AppBundle:Project p
             WHERE p.isActive = true AND
                   p.category =:id'
            )->setParameter('id', $value)
            ->getResult();
        }
        
        return $projects;
    }
    
    public function findAllSortedByOrganization()
    {
        return $this->createQueryBuilder('p')
            ->where('p.isActive = :aid')
            ->addOrderBy('p.organization', 'ASC')
            ->addOrderBy('p.topic', 'ASC')
            ->setParameter('aid', 1)
            ->getQuery()
            ->getResult();
    }
}
